### PR TITLE
release 24.04 for jammy

### PR DESCRIPTION
**Pull request by Perfect5th**

### CODE REVIEW

**Review by YanisaHS — APPROVED** [review]
Looks good!

**Comment by mcw-work** [comment]
You also need to update snapcraft.yaml to 24.04

**Comment by Perfect5th** [comment]
> You also need to update snapcraft.yaml to 24.04

Right. Done.

**Comment by srunde3** [comment]
LGTM

**Review by srunde3 — APPROVED** [review]

**Pull request merged**
