### PR TITLE
fix(snap monitoring): merge SnapMonitor into SnapManager 

### PR DESCRIPTION
**Pull request by st3v3nmw**
~This will allow the `SnapMonitor` plugin to call protected endpoints on the SnapD API that require authentication.~

To test, I've built the `.deb` locally (`dpkg-buildpackage -b -rfakeroot -us -uc`) and installled it. It can now pick up the config.

### CODE REVIEW

**Comment by srunde3** [comment]
I don't know how many consumers (if any) use this capability, but it's possible to run only the monitoring features, which run as `landscape` instead of `root`.  The idea is that it provides some "peace of mind" in case people don't feel comfortable running a process as root.  This would effectively remove that ability, so we might want to consider a more targeted solution.

I had previously worked on a "RootMonitor" idea that I abandoned in favor of adapting UbuntuProInfo to be a Manager (which run as root).  If you're interested in this approach, you could check out the branch `ubuntu-pro-livepatch-bug-lndeng-856` on my fork.  Otherwise I'd suggest adapting SnapMonitor to work natively as a Manager.

**Comment by st3v3nmw** [comment]
@srunde3 @Perfect5th,

I've ended up merging `SnapMonitor` into `SnapManager`, from the manual tests everything seems okay. I started off migrating the get config functionality into `SnapManager`  & set up an interval. But the schema of the `SNAPS` message [1] forces us to push other details of the snap... which made the `SnapMonitor` redundant hence the removal.

For existing installations that already have the SnapMonitor enabled, they'll only get a warning like this: _(which is harmless and can easily be fixed)_

```
landscape-client.landscape-client[195766]: 2024-04-05 14:05:38,437 WARNING  [MainThread] Invalid monitor plugin specified: 'SnapMonitor'. See `example.conf` for a full list of monitor plugins
```

[1]:
```python
SNAPS = Message(
    "snaps",
    {
        "snaps": KeyDict(
            {
                "installed": List(
                    KeyDict(
                        {
                            "id": Unicode(),
                            "name": Unicode(),
                            "version": Unicode(),
                            "revision": Unicode(),
                            "tracking-channel": Unicode(),
                            "hold": Unicode(),
                            "publisher": KeyDict(
                                {
                                    "username": Unicode(),
                                    "validation": Unicode(),
                                },
                                strict=False,
                            ),
                            "confinement": Unicode(),
                            "summary": Unicode(),
                            "config": Unicode(),
                        },
                        strict=False,
                        optional=[
                            "hold",
                            "summary",
                            "publisher",
                            "tracking-channel",
                            "config",
                        ],
                    ),
                ),
            },
        ),
    },
)
```

**Review by Perfect5th — APPROVED** [review]
Code LGTM. One thing to check as a follow-up, though it's not critical - if we're running on a cadence, let's make sure that we aren't sending the messages when nothing has changed since the last run. I know the code assures us this is the case, but I'd like to have some assurance from manual testing.

Still – going to approve and merge this, that can come after.

**Comment by st3v3nmw** [comment]
@Perfect5th, here are the results of the manual tests... everything looks okay.

I made these changes to `landscape/client/manager/snapmanager.py`:

image

Checking `/var/snap/landscape-client/current/var/log/landscape/manager.log`, the 1st run occurred at `17:26` which wrote some data to the tracking file after installing the new version of the snap:

```console
$ cat /var/snap/landscape-client/current/var/log/landscape/manager.log
2024-04-18 17:22:20,115 INFO     [MainThread] Got notification of impending exchange. Notifying all plugins.
2024-04-18 17:26:45,902 INFO     [MainThread] 2024-04-18T17:26: Data written to /tmp/landscape/SNAPS/2024-04-18T17:26.txt
```

---

I installed the `hello-world` snap ahead of the next run at `17:31`, this prompted the new snap data to be sent to the server:

```console
$ cat /var/snap/landscape-client/current/var/log/landscape/manager.log
2024-04-18 17:27:35,909 INFO     [MainThread] Got notification of impending exchange. Notifying all plugins.
2024-04-18 17:31:45,901 INFO     [MainThread] 2024-04-18T17:31: Data written to /tmp/landscape/SNAPS/2024-04-18T17:31.txt
```

---

Checking the differences between `2024-04-18T17:26.txt` and `2024-04-18T17:31.txt` reflects this change (`diff -u 2024-04-18T17:26.txt 2024-04-18T17:31.txt | diff-so-fancy`):

image

---

I made no changes to the installed snaps for the next two runs and no message was sent to the server:

```console
$ cat /var/snap/landscape-client/current/var/log/landscape/manager.log
2024-04-18 17:32:35,911 INFO     [MainThread] Got notification of impending exchange. Notifying all plugins.
2024-04-18 17:36:45,898 INFO     [MainThread] 2024-04-18T17:36: No data written
2024-04-18 17:41:45,923 INFO     [MainThread] 2024-04-18T17:41: No data written
```

---

Lastly, I removed the `hello-world` snap after `17:41` and another message was sent to the server. No messages were sent afterwards.

```console
$ cat /var/snap/landscape-client/current/var/log/landscape/manager.log
2024-04-18 17:46:45,898 INFO     [MainThread] 2024-04-18T17:46: Data written to /tmp/landscape/SNAPS/2024-04-18T17:46.txt
2024-04-18 17:47:35,903 INFO     [MainThread] Got notification of impending exchange. Notifying all plugins.
2024-04-18 17:51:45,905 INFO     [MainThread] 2024-04-18T17:51: No data written
2024-04-18 17:56:45,902 INFO     [MainThread] 2024-04-18T17:56: No data written
```

And the differences between `2024-04-18T17:31.txt` & `2024-04-18T17:46.txt` (`diff -u 2024-04-18T17:31.txt 2024-04-18T17:46.txt | diff-so-fancy`):

image

**Comment by Perfect5th** [comment]
Awesome. Thanks for doing that check, @st3v3nmw !

**Pull request merged**
