### PR TITLE
feat: add optional installation_request_id parameter to registration …

### PR DESCRIPTION
**Pull request by wck0**
…messages

### CODE REVIEW

**Comment by wck0** [comment]
Note: This work is in preparation for server to process this new field. Server does not do that yet, so there isn't much to test out manually.

**Comment by wck0** [comment]
> What's the difference between the hostagent_uid and this installation_request_id ?

The `hostagent_uid` uniquely identifies the Windows host machine. The `installation_request_id` uniquely identifies the activity in Landscape that initiates the installation of the WSL instance.

**Review by srunde3 — APPROVED** [review]
LGTM, left nits inline

**Comment by wck0** [comment]
Updated

**Pull request merged**
